
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook::react {
class KeyboardInsetsViewEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnPositionChanged {
      Float position;
    };

  struct OnStatusChanged {
      Float height;
    bool shown;
    bool transitioning;
    };
  void onPositionChanged(OnPositionChanged value) const;

  void onStatusChanged(OnStatusChanged value) const;
};
} // namespace facebook::react
