
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"


namespace facebook::react {

void KeyboardInsetsViewEventEmitter::onPositionChanged(OnPositionChanged event) const {
  dispatchEvent("positionChanged", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    payload.setProperty(runtime, "position", event.position);
    return payload;
  });
}


void KeyboardInsetsViewEventEmitter::onStatusChanged(OnStatusChanged event) const {
  dispatchEvent("statusChanged", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    payload.setProperty(runtime, "height", event.height);
payload.setProperty(runtime, "shown", event.shown);
payload.setProperty(runtime, "transitioning", event.transitioning);
    return payload;
  });
}

} // namespace facebook::react
