
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/debug/DebugStringConvertible.h>

namespace facebook::react {

enum class KeyboardInsetsViewMode { Auto, Manual };

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, KeyboardInsetsViewMode &result) {
  auto string = (std::string)value;
  if (string == "auto") { result = KeyboardInsetsViewMode::Auto; return; }
  if (string == "manual") { result = KeyboardInsetsViewMode::Manual; return; }
  abort();
}

static inline std::string toString(const KeyboardInsetsViewMode &value) {
  switch (value) {
    case KeyboardInsetsViewMode::Auto: return "auto";
    case KeyboardInsetsViewMode::Manual: return "manual";
  }
}

#ifdef RN_SERIALIZABLE_STATE
static inline folly::dynamic toDynamic(const KeyboardInsetsViewMode &value) {
  return toString(value);
}
#endif

class KeyboardInsetsViewProps final : public ViewProps {
 public:
  KeyboardInsetsViewProps() = default;
  KeyboardInsetsViewProps(const PropsParserContext& context, const KeyboardInsetsViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  KeyboardInsetsViewMode mode{KeyboardInsetsViewMode::Auto};
  Float extraHeight{0.0};
  bool explicitly{false};

  #ifdef RN_SERIALIZABLE_STATE
  ComponentName getDiffPropsImplementationTarget() const override;

  folly::dynamic getDiffProps(const Props* prevProps) const override;
  #endif


};

} // namespace facebook::react
