
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

KeyboardInsetsViewProps::KeyboardInsetsViewProps(
    const PropsParserContext &context,
    const KeyboardInsetsViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    mode(convertRawProp(context, rawProps, "mode", sourceProps.mode, {KeyboardInsetsViewMode::Auto})),
    extraHeight(convertRawProp(context, rawProps, "extraHeight", sourceProps.extraHeight, {0.0})),
    explicitly(convertRawProp(context, rawProps, "explicitly", sourceProps.explicitly, {false})) {}

#ifdef RN_SERIALIZABLE_STATE
ComponentName KeyboardInsetsViewProps::getDiffPropsImplementationTarget() const {
  return "KeyboardInsetsView";
}

folly::dynamic KeyboardInsetsViewProps::getDiffProps(
    const Props* prevProps) const {
  static const auto defaultProps = KeyboardInsetsViewProps();
  const KeyboardInsetsViewProps* oldProps = prevProps == nullptr
      ? &defaultProps
      : static_cast<const KeyboardInsetsViewProps*>(prevProps);
  if (this == oldProps) {
    return folly::dynamic::object();
  }
  folly::dynamic result = HostPlatformViewProps::getDiffProps(prevProps);

  if (mode != oldProps->mode) {
    result["mode"] = toDynamic(mode);
  }

  if ((extraHeight != oldProps->extraHeight) && !(std::isnan(extraHeight) && std::isnan(oldProps->extraHeight))) {
    result["extraHeight"] = extraHeight;
  }

  if (explicitly != oldProps->explicitly) {
    result["explicitly"] = explicitly;
  }
  return result;
}
#endif

} // namespace facebook::react
